output_path = "build"
zip_modules = [
  "click",
  "cython_extensions",
  "highspy",
  "map_analyzer",
  "s2protocol",
  "sc2",
]
exclude = [
  "**/__pycache__",
  "**/*.pyc",
  "**/*.pyd",
  "**/*.pyi",
  "**/*.pyx",
  "**/*-darwin.so",
  "map_analyzer/cext/mapanalyzerext*310-*",
  "map_analyzer/cext/mapanalyzerext*311-*",
  "map_analyzer/pickle_gameinfo",
  "sc2_helper/sc2_helper*310-*",
  "sc2_helper/sc2_helper*311-*",
  "sc2_helper/sc2_helper*313-*",
]
