map_pattern = "AutomatonAIE\\.SC2(MAP|Map)"
enemy_race = "Terran"
enemy_build = "Macro"
enemy_difficulty = "VeryEasy"
save_replay = "resources\\replays\\local"
bot_config = "config\\bot\\debug.toml"
log_level = "TRACE"